### ISSUE TITLE
Synta produce error on synta#go#build()

### ISSUE THREAD

**Issue by seletskiy** [kovetskiy/synta#2]
Try in `mark` repository.

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/operator/.vim/bundle/synta/pythonx/synta/__init__.py", line 35, in build
    if vim.vars['synta_go_build_recursive']:
KeyError: 'synta_go_build_recursive'
```

**Comment by kovetskiy** [comment]
Didn't work for me because I have that variable :smile:
